name: Coder Thoughts
description: Coder Thoughts on software, technology and programming.
copyRights: Copyright © 2018 - Piotr Mionskowski Blog content licensed under the Creative Commons
author: piotr
twitter: 
  username: miensol
social:
  name: Piotr Mionskowski
  links:
    - https://twitter.com/miensol
    - https://github.com/miensol
    - https://stackoverflow.com/users/155213/miensol
locale: en_US
url: https://miensol.pl
logo: /image/me.jpg
paginate: 5
encoding: utf-8
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist